<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace></RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\CapaNegocios\EntidadesEmpresariales\GRH\GRH.Entidades\GRH.Entidades.vbproj" />
    <ProjectReference Include="..\..\..\..\CapaNegocios\InterfacesServicios\GRH\GRH.InterfacesServicios\GRH.InterfacesServicios.vbproj" />
    <ProjectReference Include="..\..\..\Helper\Helper.AccesoDatos\Helper.AccesoDatos.vbproj" />
  </ItemGroup>
</Project>
