<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace></RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\CapaNegocios\EntidadesEmpresariales\CAJ\CAJ.Entidades\CAJ.Entidades.vbproj" />
    <ProjectReference Include="..\..\..\..\CapaNegocios\InterfacesServicios\CAJ\CAJ.InterfacesServicios\CAJ.InterfacesServicios.vbproj" />
    <ProjectReference Include="..\..\..\Helper\Helper.AccesoDatos\Helper.AccesoDatos.vbproj" />
  </ItemGroup>
</Project>
