<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CORLAD.Tests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CapaInfraestructuraComun\AdminitracionOperacional\GEN.Infraestructura\GEN.Infraestructura.vbproj" />
    <ProjectReference Include="..\..\CapaAccesoDatos\Helper\Helper.AccesoDatos\Helper.AccesoDatos.vbproj" />
    <ProjectReference Include="..\..\CapaNegocios\EntidadesEmpresariales\CLI\CLI.Entidades\CLI.Entidades.vbproj" />
    <ProjectReference Include="..\..\CapaNegocios\InterfacesServicios\CLI\CLI.InterfacesServicios\CLI.InterfacesServicios.vbproj" />
    <ProjectReference Include="..\..\CapaNegocios\FlujoTrabajoEmpresariales\CLI\CLI.FlujoTrabajo\CLI.FlujoTrabajo.vbproj" />
  </ItemGroup>

</Project>