<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace></RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\EntidadesEmpresariales\RPT\RPT.Entidades\RPT.Entidades.vbproj" />
    <ProjectReference Include="..\..\..\InterfacesServicios\RPT\RPT.InterfacesServicios\RPT.InterfacesServicios.vbproj" />
    <ProjectReference Include="..\..\..\..\CapaAccesoDatos\ComponenteLogicoAccesoDatos\RPT\RPT.AccesoDatos\RPT.AccesoDatos.vbproj" />
    <ProjectReference Include="..\..\..\..\CapaInfraestructuraComun\AdminitracionOperacional\GEN.Infraestructura\GEN.Infraestructura.vbproj" />
  </ItemGroup>
</Project>
