<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace></RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\EntidadesEmpresariales\PRE\PRE.Entidades\PRE.Entidades.vbproj" />
    <ProjectReference Include="..\..\..\InterfacesServicios\PRE\PRE.InterfacesServicios\PRE.InterfacesServicios.vbproj" />
    <ProjectReference Include="..\..\..\..\CapaAccesoDatos\ComponenteLogicoAccesoDatos\PRE\PRE.AccesoDatos\PRE.AccesoDatos.vbproj" />
    <ProjectReference Include="..\..\..\..\CapaInfraestructuraComun\AdminitracionOperacional\GEN.Infraestructura\GEN.Infraestructura.vbproj" />
  </ItemGroup>
</Project>
